export const promos = [
  {
    brand: "kimukatsu",
    imageBrand: "kimukatsu.png",
    jenis: "Free",
    subjenis: "Chizu Kani Mayo",
    imageJenis: "kimukatsu.jpg",
    waktuBerakhir: "ENDS TOMORROW",
  },
  {
    brand: "genki sushi",
    imageBrand: "genki_sushi.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "genki_sushi.jpg",
    waktuBerakhir: "5 DAYS LEFT",
  },
  {
    brand: "baskin robbins",
    imageBrand: "baskin_robbins.png",
    jenis: "Buy 1",
    subjenis: "Get 1",
    imageJenis: "baskin_robbins.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "cupbop",
    imageBrand: "cupbop.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "cupbop.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "pepper lunch",
    imageBrand: "pepper_lunch.png",
    jenis: "Free",
    subjenis: "Chicken Pepper Rice",
    imageJenis: "pepper_lunch.jpg",
    waktuBerakhir: "UNTIL AUG'22",
  },
  {
    brand: "kimukatsu",
    imageBrand: "kimukatsu.png",
    jenis: "Free",
    subjenis: "Chizu Kani Mayo",
    imageJenis: "kimukatsu.jpg",
    waktuBerakhir: "ENDS TOMORROW",
  },
  {
    brand: "genki sushi",
    imageBrand: "genki_sushi.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "genki_sushi.jpg",
    waktuBerakhir: "5 DAYS LEFT",
  },
  {
    brand: "baskin robbins",
    imageBrand: "baskin_robbins.png",
    jenis: "Buy 1",
    subjenis: "Get 1",
    imageJenis: "baskin_robbins.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "cupbop",
    imageBrand: "cupbop.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "cupbop.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "pepper lunch",
    imageBrand: "pepper_lunch.png",
    jenis: "Free",
    subjenis: "Chicken Pepper Rice",
    imageJenis: "pepper_lunch.jpg",
    waktuBerakhir: "UNTIL AUG'22",
  },
  {
    brand: "kimukatsu",
    imageBrand: "kimukatsu.png",
    jenis: "Free",
    subjenis: "Chizu Kani Mayo",
    imageJenis: "kimukatsu.jpg",
    waktuBerakhir: "ENDS TOMORROW",
  },
  {
    brand: "genki sushi",
    imageBrand: "genki_sushi.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "genki_sushi.jpg",
    waktuBerakhir: "5 DAYS LEFT",
  },
  {
    brand: "baskin robbins",
    imageBrand: "baskin_robbins.png",
    jenis: "Buy 1",
    subjenis: "Get 1",
    imageJenis: "baskin_robbins.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "cupbop",
    imageBrand: "cupbop.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "cupbop.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "pepper lunch",
    imageBrand: "pepper_lunch.png",
    jenis: "Free",
    subjenis: "Chicken Pepper Rice",
    imageJenis: "pepper_lunch.jpg",
    waktuBerakhir: "UNTIL AUG'22",
  },
  {
    brand: "kimukatsu",
    imageBrand: "kimukatsu.png",
    jenis: "Free",
    subjenis: "Chizu Kani Mayo",
    imageJenis: "kimukatsu.jpg",
    waktuBerakhir: "ENDS TOMORROW",
  },
  {
    brand: "genki sushi",
    imageBrand: "genki_sushi.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "genki_sushi.jpg",
    waktuBerakhir: "5 DAYS LEFT",
  },
  {
    brand: "baskin robbins",
    imageBrand: "baskin_robbins.png",
    jenis: "Buy 1",
    subjenis: "Get 1",
    imageJenis: "baskin_robbins.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "cupbop",
    imageBrand: "cupbop.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "cupbop.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "pepper lunch",
    imageBrand: "pepper_lunch.png",
    jenis: "Free",
    subjenis: "Chicken Pepper Rice",
    imageJenis: "pepper_lunch.jpg",
    waktuBerakhir: "UNTIL AUG'22",
  },
  {
    brand: "kimukatsu",
    imageBrand: "kimukatsu.png",
    jenis: "Free",
    subjenis: "Chizu Kani Mayo",
    imageJenis: "kimukatsu.jpg",
    waktuBerakhir: "ENDS TOMORROW",
  },
  {
    brand: "genki sushi",
    imageBrand: "genki_sushi.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "genki_sushi.jpg",
    waktuBerakhir: "5 DAYS LEFT",
  },
  {
    brand: "baskin robbins",
    imageBrand: "baskin_robbins.png",
    jenis: "Buy 1",
    subjenis: "Get 1",
    imageJenis: "baskin_robbins.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "cupbop",
    imageBrand: "cupbop.png",
    jenis: "Buy 1",
    subjenis: "Get 1 Free",
    imageJenis: "cupbop.jpg",
    waktuBerakhir: "12 DAYS LEFT",
  },
  {
    brand: "pepper lunch",
    imageBrand: "pepper_lunch.png",
    jenis: "Free",
    subjenis: "Chicken Pepper Rice",
    imageJenis: "pepper_lunch.jpg",
    waktuBerakhir: "UNTIL AUG'22",
  },
];